.TH LIBPARSEPSF 7 LIBPARSEPSF
.SH NAME
libparsepsf \- Library for interpreting PSF (PC Screen Font) files.
.SH DESCRIPTION
.B libparsepsf
is a C library for interpreting PSF (PC Screen Font) files.
It can be used to examine the contents of a font file, and look up
glyphs to use a for a text. It does not render text, instead the
user is given enough information to implement it's own rendering;
nor is the library capable of creating PSF files.
.SH SEE ALSO
.BR libparsepsf.h (0),
.BR libparsepsf_parse_font (3),
.BR libparsepsf_get_glyph (3),
.BR libparsepsf_destroy_font (3)
